version: '3.8'

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wordflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s1159mG7yV
    volumes:
      - './.docker-cache/postgresql/data:/var/lib/postgresql/data'
